services:
    docker-express-app:
        image: fialco/docker-express-app:latest
        ports:
            - 8080:8080
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        restart: unless-stopped

    watchtower:
        image: containrrr/watchtower
        environment:
        -  WATCHTOWER_POLL_INTERVAL=60
        -  WATCHTOWER_LABEL_ENABLE=true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower
